from setuptools import setup

setup(
    name='groupchoiser',
    version='1.0',
    packages=['groupchoiser', 'groupchoiser.venv', 'groupchoiser.venv.Lib', 'groupchoiser.venv.Lib.site-packages',
              'groupchoiser.venv.Lib.site-packages.pip', 'groupchoiser.venv.Lib.site-packages.pip._vendor',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.idna',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.toml',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.pep517',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.certifi',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.chardet',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.chardet.cli',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.distlib',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.distlib._backport',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.msgpack',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.util',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.colorama',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.progress',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.requests',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.packaging',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.resolvelib',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.resolvelib.compat',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.cachecontrol',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.webencodings',
              'groupchoiser.venv.Lib.site-packages.pip._vendor.pkg_resources',
              'groupchoiser.venv.Lib.site-packages.pip._internal',
              'groupchoiser.venv.Lib.site-packages.pip._internal.cli',
              'groupchoiser.venv.Lib.site-packages.pip._internal.req',
              'groupchoiser.venv.Lib.site-packages.pip._internal.vcs',
              'groupchoiser.venv.Lib.site-packages.pip._internal.index',
              'groupchoiser.venv.Lib.site-packages.pip._internal.utils',
              'groupchoiser.venv.Lib.site-packages.pip._internal.models',
              'groupchoiser.venv.Lib.site-packages.pip._internal.network',
              'groupchoiser.venv.Lib.site-packages.pip._internal.commands',
              'groupchoiser.venv.Lib.site-packages.pip._internal.operations',
              'groupchoiser.venv.Lib.site-packages.pip._internal.operations.build',
              'groupchoiser.venv.Lib.site-packages.pip._internal.operations.install',
              'groupchoiser.venv.Lib.site-packages.pip._internal.resolution',
              'groupchoiser.venv.Lib.site-packages.pip._internal.resolution.legacy',
              'groupchoiser.venv.Lib.site-packages.pip._internal.resolution.resolvelib',
              'groupchoiser.venv.Lib.site-packages.pip._internal.distributions',
              'groupchoiser.venv.Lib.site-packages.setuptools', 'groupchoiser.venv.Lib.site-packages.setuptools.extern',
              'groupchoiser.venv.Lib.site-packages.setuptools._vendor',
              'groupchoiser.venv.Lib.site-packages.setuptools._vendor.packaging',
              'groupchoiser.venv.Lib.site-packages.setuptools.command',
              'groupchoiser.venv.Lib.site-packages.setuptools._distutils',
              'groupchoiser.venv.Lib.site-packages.setuptools._distutils.command',
              'groupchoiser.venv.Lib.site-packages.pkg_resources',
              'groupchoiser.venv.Lib.site-packages.pkg_resources.extern',
              'groupchoiser.venv.Lib.site-packages.pkg_resources._vendor',
              'groupchoiser.venv.Lib.site-packages.pkg_resources._vendor.packaging',
              'groupchoiser.venv.Lib.site-packages._distutils_hack', 'groupchoiser.students'],
    url='',
    license='',
    author='jordan diaz',
    author_email='jojo',
    description='jojo',
    entry_points={
        'console_scripts': ["groupchoiser=groupchoiser.main:main"]
    },
)
